import XCTest
@testable import WazaProto

/// Shape-validation tests for `Secrets`. The file itself is gitignored and
/// regenerated by `scripts/refresh-secrets.sh`; these tests guard against the
/// script (or a hand-edit) emitting malformed values.
final class SecretsTests: XCTestCase {

    func testInviteSigningSecretMeetsHS256Strength() throws {
        XCTAssertFalse(Secrets.inviteSigningSecret.isEmpty)
        let decoded = try XCTUnwrap(
            Data(base64Encoded: Secrets.inviteSigningSecret),
            "inviteSigningSecret must be base64-decodable"
        )
        XCTAssertGreaterThanOrEqual(decoded.count, 32, "HS256 requires ≥256 bits of key material")
    }

    func testPublisherSigningSecretMeetsHS256Strength() throws {
        XCTAssertFalse(Secrets.publisherSigningSecret.isEmpty)
        let decoded = try XCTUnwrap(
            Data(base64Encoded: Secrets.publisherSigningSecret),
            "publisherSigningSecret must be base64-decodable"
        )
        XCTAssertGreaterThanOrEqual(decoded.count, 32, "HS256 requires ≥256 bits of key material")
    }
}
